### ISSUE TITLE
Is it use on Dell 7347?

### ISSUE THREAD

**Issue by alex-cham** [MoozIiSP/dell-7348-hackintosh#3]
I don't know the difference.

**Comment by MoozIiSP** [comment]
As far as I know, Dell 7347 has 4th Gen Intel CPU, so it may not be used on Dell 7347 without any modification. So based on it to install MacOS, you should re-patch SSDT patch to fit your Dell 7347, check `platform-id` of GPU and available `layout-id` of sound card, and modify their on `config.plist`  to make it work.

**Comment by alex-cham** [comment]
Thank you. I've made it.
